version: 0.2

phases:
 pre_build:
  commands:
   - echo "Inside pre_build"
 build:
  commands:
   - echo "Inside Build"
   - cd aws-cicd
   - mvn package war:exploded
 post_build:
  commands:
   - echo "Inside post_build"
   - cd ..
   - mv aws-cicd/target/aws-cicd-0.0.1-SNAPSHOT/* aws-cicd-0.0.1-SNAPSHOT/*	
artifacts:
 files:
  - aws-cicd-0.0.1-SNAPSHOT/*