version: 0.2

phases:
 pre_build:
  commands:
   - echo "Inside pre_build"
 build:
  commands:
   - echo "Inside Build"
   - cd aws-cicd
   - mvn clean package
 post_build:
  commands:
   - echo "Inside post_build"	
artifacts:
 files:
  - aws/cicd/target/aws-cicd-0.0.1-SNAPSHOT.war